# coding=utf-8
"""Tests for Pulp 3's auto generated API docs.

For more information, see the documentation on `REST API Reference
<https://docs.pulpproject.org/en/3.0/nightly/integration_guide/rest_api/index.html>`_.
"""
import unittest

from pulp_smash import api, config, selectors, utils
from pulp_smash.tests.pulp3.constants import DOCS_PATH
from pulp_smash.tests.pulp3.pulpcore.utils import set_up_module as setUpModule  # noqa pylint:disable=unused-import
from pulp_smash.tests.pulp3.utils import get_auth


class AutoGeneratedDocsTestCase(unittest.TestCase, utils.SmokeTest):
    """Verify whether the auto generated docs are available."""

    def test_all(self):
        """Verify whether the auto generated docs are available."""
        cfg = config.get_config()
        if selectors.bug_is_untestable(3142, cfg.pulp_version):
            self.skipTest('https://pulp.plan.io/issues/3142')
        if selectors.bug_is_untestable(3420, cfg.pulp_version):
            self.skipTest('https://pulp.plan.io/issues/3420')
        client = api.Client(cfg, api.code_handler)
        client.request_kwargs['auth'] = get_auth()
        client.get(DOCS_PATH)
